name: Update Stock Data

on:
  schedule:
    - cron: '0 10 * * 1-5' # 預設週一至週五 18:00 (UTC+8) 執行
  workflow_dispatch:        # 允許你手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas yfinance

      - name: Run main script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add history.json results.json
          # 檢查是否有變更，若無變更則不執行 commit，避免錯誤
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update stock data" && git push)
